docker_builder:
  name: FreeIPA server in docker
  env:
    CIRRUS_ARCH: arm64
    matrix:
      - os: fedora-42
  config_script:
    - id
    - ls -la /dev/std*
    - ls -la /proc/self/fd
    - useradd -m -u 200000 -U -G docker testuser
    - echo dockremap:200000:65536 > /etc/subuid
    - echo dockremap:200000:65536 > /etc/subgid
    - echo '{"userns-remap":"default"}' > /etc/docker/daemon.json
    - systemctl restart docker
  build_script: runuser -u testuser -- docker build -t localhost/freeipa/freeipa-server:$os -f Dockerfile.$os .
  test_script: runuser -u testuser -- tests/run-master-and-replica.sh localhost/freeipa/freeipa-server:$os

docker_builder:
  name: FreeIPA server in podman
  env:
    CIRRUS_ARCH: arm64
    matrix:
      - os: almalinux-10
  install_script:
    - apt update && apt install -y podman
    - useradd -m -u 200000 -U testuser
    - echo testuser:200001:65535 > /etc/subuid
    - echo testuser:200001:65535 > /etc/subgid
  build_script: su -l testuser -c "cd $PWD && podman build -t localhost/freeipa/freeipa-server:$os -f Dockerfile.$os ."
  test_script: su -l testuser -c "cd $PWD && docker=podman tests/run-master-and-replica.sh localhost/freeipa/freeipa-server:$os"
