language: minimal
os: linux
dist: focal

virt: vm
arch: arm64-graviton2
group: edge

services:
- docker

install:
- if test -n "$ca" ; then sudo apt-get install -y libnss3-tools ; fi
- export docker=${docker:-docker}
- if test "$docker" == "sudo podman" -o "$docker" == 'podman' ; then . /etc/os-release && echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list && curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add - && sudo apt-get update -y && sudo apt-get install -y podman containernetworking-plugins ; fi
- if [ "$docker" = 'podman' ] ; then sudo apt-get install -y fuse-overlayfs uidmap slirp4netns ; fi

before_script:
- perl -e 'print map "$_=$ENV{$_}".chr(10), sort keys %ENV'

script:
- $docker build -t systemd -f Dockerfile.$dockerfile .
- find /sys/fs/cgroup/ -type d -exec stat \{\} \; && cat /proc/self/cgroup && ps auxww
- ( sleep 10 ; $docker rm -f systemd ) & systemd-run --scope --user $docker run --log-level debug --name systemd -ti --rm systemd /usr/sbin/init --log-level debug

after_failure:
- sudo journalctl -l | grep -i seccomp

stages:
- test

jobs:
  include:
    - stage: test
      env: dockerfile=fedora-34 docker=podman
