name: Install and start CRI-O
runs:
  using: composite
  steps:
    - run: |
        [ -n "$CRIO_VERSION" ] || exit 1
        curl -fsSL https://download.opensuse.org/repositories/isv:/cri-o:/stable:/$CRIO_VERSION/deb/Release.key \
            | gpg --dearmor | sudo tee /etc/apt/keyrings/cri-o-apt-keyring.gpg > /dev/null
        echo "deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://download.opensuse.org/repositories/isv:/cri-o:/stable:/$CRIO_VERSION/deb/ /" \
            | sudo tee /etc/apt/sources.list.d/cri-o.list

        sudo apt update
        sudo apt install -y cri-o

        sudo cp /etc/cni/net.d/10-crio-bridge.conflist.disabled /etc/cni/net.d/10-crio-bridge.conflist
        # Workaround ImageInspectError of Kubernetes "system" pods caused by
        #   short name mode is enforcing, but image name ... returns ambiguous list
        # for images like rancher/local-path-provisioner:v0.0.31 
        # due to multiple unqualified-search-registries entries in /etc/containers/registries.conf.d/crio.conf
        echo 'unqualified-search-registries = ["docker.io"]' | sudo tee /etc/containers/registries.conf.d/no-unqualified-quay.conf
        sudo systemctl start crio.service
      shell: bash -euxo pipefail {0}
