name: Build and test FreeIPA containers
run-name: Build and test FreeIPA containers${{ github.event_name == 'workflow_dispatch' && format(' ({0})', inputs.os) || ''}}

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      os:
        description: OS / Dockerfile
        type: choice
        options:
          - all
          - fedora-42
          - fedora-41
          - almalinux-10
          - almalinux-9
          - almalinux-8
          - rocky-9
          - rocky-8
          - centos-10-stream
          - centos-9-stream
  schedule:
    - cron: '15 4 * * 1,3,5'

jobs:
  init:
    name: Process workflow inputs
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      os: ${{ steps.generate-os-list-dispatch-one.outputs.os }}${{ steps.generate-os-list-all.outputs.os }}
    steps:
      - id: generate-os-list-dispatch-one
        if: github.event_name == 'workflow_dispatch' && inputs.os != 'all'
        run: echo 'os=["${{ inputs.os }}"]' | tee $GITHUB_OUTPUT
      - uses: actions/checkout@v4
        if: github.event_name != 'workflow_dispatch' || inputs.os == 'all'
      - id: generate-os-list-all
        if: github.event_name != 'workflow_dispatch' || inputs.os == 'all'
        run: |
          yq '.on.workflow_dispatch.inputs.os.options | map(select(. != "all"))' .github/workflows/build-test.yaml -o json \
            | jq -c . | sed 's/^/os=/' | tee $GITHUB_OUTPUT
  build:
    name: Build image
    runs-on: ubuntu-24.04${{ (matrix.arch == 'arm64' && '-arm') || (matrix.arch == 'x86_64' && '') }}
    needs: [ init ]
    if: needs.init.outputs.os != '[]'
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(needs.init.outputs.os ) }}
        arch: [ x86_64, arm64 ]
        docker: [ docker ]
        exclude:
          - os: fedora-41
            arch: arm64
          - os: centos-10-stream
            arch: x86_64
          - os: centos-9-stream
            arch: arm64
          - os: almalinux-8
            arch: arm64
          - os: rocky-8
            arch: arm64
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir -p build-status/${{ matrix.os }}-${{ matrix.arch }}
          ( echo "- os: ${{ matrix.os }}" ; echo "  arch: ${{ matrix.arch }}" ) > build-status/${{ matrix.os }}-${{ matrix.arch }}/build-dist
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: build-status-${{ matrix.os }}-${{ matrix.arch }}
          path: build-status
          retention-days: 1

  test-plan:
    name: FreeIPA test plan
    runs-on: ubuntu-latest
    needs: [ build ]
    timeout-minutes: 1
    outputs:
      matrix-run: ${{ steps.produce-matrix.outputs.matrix-run }}
      matrix-test-upgrade: ${{ steps.produce-matrix.outputs.matrix-test-upgrade }}
      matrix-k8s: ${{ steps.produce-matrix.outputs.matrix-k8s }}
      matrix-push: ${{ steps.produce-matrix.outputs.matrix-push }}
      matrix-push-data: ${{ steps.produce-matrix.outputs.matrix-push-data }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: build-status-*
          path: build-status
          merge-multiple: true
      - name: Amend the .github/build-test-params.yaml with information about built images
        run: |
          (
              echo 'build-dist:'
              yq '.jobs.build.strategy.matrix.arch as $arch | .on.workflow_dispatch.inputs.os.options | .[] + "-" + $arch[]' .github/workflows/build-test.yaml \
              | while read i ; do
                if [ -f build-status/$i/build-dist ] ; then cat build-status/$i/build-dist ; fi
              done
              echo 'fresh-dist:'
              cat build-status/*/fresh-image || :
              cat .github/build-test-params.yaml
          ) | yq . - -o json | tee .github/build-test-data.json
        shell: bash
      - id: produce-matrix
        run: |
          jq -f ci/generate-test-matrix.jq -c --arg job run .github/build-test-data.json \
              | ( echo -n 'matrix-run=' >> $GITHUB_OUTPUT ; tee -a $GITHUB_OUTPUT )
          jq -f ci/generate-test-matrix.jq -c --arg job test-upgrade .github/build-test-data.json \
              | ( echo -n 'matrix-test-upgrade=' >> $GITHUB_OUTPUT ; tee -a $GITHUB_OUTPUT )
          jq -f ci/generate-test-matrix.jq -c --arg job k8s .github/build-test-data.json \
              | ( echo -n 'matrix-k8s=' >> $GITHUB_OUTPUT ; tee -a $GITHUB_OUTPUT )
          jq -f ci/generate-test-matrix.jq -c --arg job push .github/build-test-data.json \
              | ( echo -n 'matrix-push=' >> $GITHUB_OUTPUT ; tee -a $GITHUB_OUTPUT )
          jq -f ci/generate-test-matrix.jq -c --arg job push-data .github/build-test-data.json \
              | ( echo -n 'matrix-push-data=' >> $GITHUB_OUTPUT ; tee -a $GITHUB_OUTPUT )
        shell: bash
      - run: |
          echo '${{ steps.produce-matrix.outputs.matrix-run }}' \
              | jq -rf ci/test-matrix-to-html.jq --arg job run --argjson build-dist "$( jq -c '.["build-dist"]' .github/build-test-data.json )" >> $GITHUB_STEP_SUMMARY
        shell: bash
      - run: |
          echo '${{ steps.produce-matrix.outputs.matrix-test-upgrade }}' \
              | jq -rf ci/test-matrix-to-html.jq --arg job test-upgrade --argjson build-dist "$( jq -c '.["build-dist"]' .github/build-test-data.json )" >> $GITHUB_STEP_SUMMARY
        shell: bash
      - run: |
          echo '${{ steps.produce-matrix.outputs.matrix-k8s }}' \
              | jq -rf ci/test-matrix-to-html.jq --arg job k8s --argjson build-dist "$( jq -c '.["build-dist"]' .github/build-test-data.json )" >> $GITHUB_STEP_SUMMARY
        shell: bash
      - run: jq -n -rf ci/test-matrix-to-html.jq --arg job legend >> $GITHUB_STEP_SUMMARY
        shell: bash

