name: Build and test FreeIPA containers

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build image on Testing Farm
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        os: [ fedora-38 ]
    steps:
      - uses: actions/checkout@v3
      - name: Run build on Testing Farm
        uses: sclorg/testing-farm-as-github-action@e0698058cb49fcd6ebae84ade08d8ce8044a31c4
        with:
          api_key: ${{ secrets.TF_API_KEY }}
          git_url: ${{ github.server_url }}/${{ github.repository }}
          git_ref: ${{ github.ref_name }}
          update_pull_request_status: "false"
          tf_scope: public
          compose: CentOS-Stream-9

