name: Build and test FreeIPA containers

on:
  push:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        os: [ fedora-rawhide, fedora-41, fedora-40, centos-9-stream, rocky-9, rocky-8, almalinux-9, almalinux-8 ]
        docker: [ docker ]
    timeout-minutes: 15
    steps:
      - name: Create directory for artifacts
        run: mkdir freeipa-server-${{ matrix.os }}
      - name: Save image
        run: echo ${{ matrix.os }} ${{ matrix.docker }} > freeipa-server-${{ matrix.os }}/freeipa-server-${{ matrix.os }}.out
      - uses: actions/upload-artifact@v4
        with:
          name: freeipa-server-${{ matrix.os }}
          path: freeipa-server-${{ matrix.os }}
          retention-days: 1

  master-and-replica:
    name: Run
    runs-on: ${{ matrix.runs-on }}
    needs: [ build ]
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: fedora-41
            runtime: docker
            runs-on: ubuntu-24.04
          - os: fedora-41
            readonly: --read-only
            volume: freeipa-data
            runtime: docker
            runs-on: ubuntu-24.04
          - os: fedora-41
            readonly: --read-only
            runtime: docker
            runs-on: ubuntu-24.04
          - os: fedora-40
            runtime: docker
            runs-on: ubuntu-24.04
          - os: fedora-rawhide
            runtime: docker
            runs-on: ubuntu-24.04
          - os: fedora-rawhide
            readonly: --read-only
            ca: --external-ca
            volume: freeipa-data
            runtime: docker
            runs-on: ubuntu-24.04
          - os: centos-9-stream
            runtime: docker
            runs-on: ubuntu-24.04
          - os: centos-9-stream
            readonly: --read-only
            volume: freeipa-data
            runtime: docker
            runs-on: ubuntu-24.04
          - os: centos-9-stream
            readonly: --read-only
            ca: --external-ca
            runtime: docker
            runs-on: ubuntu-24.04
          - os: almalinux-9
            runtime: docker
            runs-on: ubuntu-24.04
          - os: rocky-8
            runtime: docker
            runs-on: ubuntu-24.04

          - os: fedora-rawhide
            readonly: --read-only
            runtime: docker rootless
            runs-on: ubuntu-24.04
          - os: fedora-41
            readonly: --read-only
            volume: freeipa-data
            runtime: docker rootless
            runs-on: ubuntu-24.04
          - os: rocky-9
            readonly: --read-only
            runtime: docker rootless
            runs-on: ubuntu-24.04
          - os: almalinux-8
            readonly: --read-only
            volume: freeipa-data
            runtime: docker rootless
            runs-on: ubuntu-24.04

          - os: fedora-41
            runtime: sudo podman
            runs-on: ubuntu-24.04
          - os: centos-9-stream
            runtime: sudo podman
            runs-on: ubuntu-24.04

          - os: fedora-41
            readonly: --read-only
            volume: freeipa-data
            runtime: podman
            runs-on: ubuntu-24.04
          - os: almalinux-9
            readonly: --read-only
            volume: freeipa-data
            runtime: podman
            runs-on: ubuntu-24.04
          - os: rocky-8
            readonly: --read-only
            runtime: podman
            runs-on: ubuntu-24.04

          - os: fedora-rawhide
            readonly: --read-only
            volume: freeipa-data
            runtime: podman
            runs-on: ubuntu-22.04
          - os: almalinux-8
            readonly: --read-only
            volume: freeipa-data
            runtime: podman
            runs-on: ubuntu-22.04
          - os: rocky-9
            readonly: --read-only
            runtime: podman
            runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Save run output
        id: save
        run: |
          echo run=$SRANDOM | tee -a $GITHUB_OUTPUT
          mkdir run && cd run
          mkdir "runtime=${{ matrix.runtime }}" && cd *
          mkdir "readonly=${{ matrix.readonly }}" && cd *
          mkdir "ca=${{ matrix.ca }}" && cd *
          mkdir "volume=${{ matrix.volume }}" && cd *
          mkdir "runs-on=${{ matrix.runs-on }}" && cd *
          echo "os=${{ matrix.os }}" > "os=${{ matrix.os }}"
      - uses: actions/upload-artifact@v4
        with:
          name: run-${{ steps.save.outputs.run }}
          path: run
          retention-days: 1

  test-upgrade:
    name: Upgrade
    runs-on: ${{ matrix.runs-on }}
    needs: [ build ]
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: fedora-rawhide
            data-from: fedora-41
            runtime: docker
            runs-on: ubuntu-24.04
          - os: fedora-41
            data-from: fedora-41
            runtime: docker
            runs-on: ubuntu-24.04
          - os: fedora-41
            data-from: fedora-40
            runtime: docker
            runs-on: ubuntu-24.04
          - os: fedora-40
            data-from: fedora-39
            runtime: docker
            runs-on: ubuntu-24.04
          - os: rocky-8
            data-from: centos-8-certs-updated-data
            runtime: docker
            runs-on: ubuntu-24.04

          - os: fedora-41
            data-from: fedora-40
            runtime: podman
            runs-on: ubuntu-24.04
          - os: almalinux-8
            data-from: centos-8-certs-updated-data
            runtime: podman
            runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - name: Save upgrade output
        id: save
        run: |
          echo run=$SRANDOM | tee -a $GITHUB_OUTPUT
          mkdir upgrade && cd upgrade
          mkdir "runtime=${{ matrix.runtime }}" && cd *
          mkdir "data-from=${{ matrix.data-from }}" && cd *
          mkdir "runs-on=${{ matrix.runs-on }}" && cd *
          echo "os=${{ matrix.os }}" > "os=${{ matrix.os }}"
      - uses: actions/upload-artifact@v4
        with:
          name: upgrade-${{ steps.save.outputs.run }}
          path: upgrade
          retention-days: 1

  push-after-success:
    name: Push images to registries
    runs-on: ubuntu-24.04
    needs: [ master-and-replica, test-upgrade ]
    timeout-minutes: 30
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: run-*
          path: run
          merge-multiple: true
      - run: find run -type f
      - uses: actions/download-artifact@v4
        with:
          pattern: upgrade-*
          path: upgrade
          merge-multiple: true
      - run: find upgrade -type f

